# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import time_period_pb2 as time__period__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in time_period_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimePeriodServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimePeriod = channel.unary_unary(
                '/work_ticket.TimePeriodService/GetTimePeriod',
                request_serializer=time__period__pb2.GetTimePeriodRequest.SerializeToString,
                response_deserializer=time__period__pb2.TimePeriod.FromString,
                _registered_method=True)
        self.ListTimePeriods = channel.unary_unary(
                '/work_ticket.TimePeriodService/ListTimePeriods',
                request_serializer=time__period__pb2.ListTimePeriodsRequest.SerializeToString,
                response_deserializer=time__period__pb2.ListTimePeriodsResponse.FromString,
                _registered_method=True)


class TimePeriodServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTimePeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTimePeriods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimePeriodServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimePeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimePeriod,
                    request_deserializer=time__period__pb2.GetTimePeriodRequest.FromString,
                    response_serializer=time__period__pb2.TimePeriod.SerializeToString,
            ),
            'ListTimePeriods': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTimePeriods,
                    request_deserializer=time__period__pb2.ListTimePeriodsRequest.FromString,
                    response_serializer=time__period__pb2.ListTimePeriodsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'work_ticket.TimePeriodService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('work_ticket.TimePeriodService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimePeriodService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTimePeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.TimePeriodService/GetTimePeriod',
            time__period__pb2.GetTimePeriodRequest.SerializeToString,
            time__period__pb2.TimePeriod.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTimePeriods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/work_ticket.TimePeriodService/ListTimePeriods',
            time__period__pb2.ListTimePeriodsRequest.SerializeToString,
            time__period__pb2.ListTimePeriodsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
