"""add_color_to_schema_class

Revision ID: 194c8bc63f48
Revises: 6c335a125565
Create Date: 2026-02-08 22:43:13.675168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194c8bc63f48'
down_revision: Union[str, Sequence[str], None] = '6c335a125565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema_classes', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema_classes', 'color')
    # ### end Alembic commands ###
