"""add action description

Revision ID: 3ddb398b8111
Revises: 8e8a5581c064
Create Date: 2026-02-06 16:02:09.453373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddb398b8111'
down_revision: Union[str, Sequence[str], None] = '8e8a5581c064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_definitions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_definitions', 'description')
    # ### end Alembic commands ###
