"""add_source_id_to_graph_entity

Revision ID: 59353a272550
Revises: 80a7d5ebda72
Create Date: 2026-02-12 11:11:40.354506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59353a272550'
down_revision: Union[str, Sequence[str], None] = '80a7d5ebda72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_entities', sa.Column('source_id', sa.String(length=500), nullable=True))
    op.create_index('idx_entities_type_source', 'graph_entities', ['entity_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_graph_entities_source_id'), 'graph_entities', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_entities_source_id'), table_name='graph_entities')
    op.drop_index('idx_entities_type_source', table_name='graph_entities')
    op.drop_column('graph_entities', 'source_id')
    # ### end Alembic commands ###
